--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/09/2018 14:25:03
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';