--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/09/2018 14:40:43
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE servicioderenta;

--
-- Drop table `autos`
--
DROP TABLE IF EXISTS autos;

--
-- Set default database
--
USE servicioderenta;

--
-- Create table `autos`
--
CREATE TABLE autos (
  codAuto int(11) NOT NULL AUTO_INCREMENT,
  placa int(11) NOT NULL,
  tipo varchar(25) NOT NULL,
  capacidad int(11) NOT NULL,
  modelo year(4) NOT NULL,
  estado varchar(10) NOT NULL,
  precio int(11) NOT NULL,
  PRIMARY KEY (codAuto)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `placa` on table `autos`
--
ALTER TABLE autos
ADD UNIQUE INDEX placa (placa);

-- 
-- Dumping data for table autos
--
-- Table servicioderenta.autos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;