--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/9/2018 14:48:12
-- Server version: 5.5.5-10.1.30-MariaDB
-- Client version: 4.1
--


--
-- Definition for database servicioderenta
--
DROP DATABASE IF EXISTS servicioderenta;
CREATE DATABASE servicioderenta
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE servicioderenta;

--
-- Definition for table administrativo
--
CREATE TABLE administrativo (
  codigoAdministrativo INT(11) NOT NULL AUTO_INCREMENT,
  codigoAgencia INT(11) DEFAULT NULL,
  CI INT(11) DEFAULT NULL,
  nroContacto INT(11) DEFAULT NULL,
  PRIMARY KEY (codigoAdministrativo)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table agencia
--
CREATE TABLE agencia (
  codigoagencia INT(11) NOT NULL AUTO_INCREMENT,
  direccion VARCHAR(50) DEFAULT NULL,
  ciudad VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (codigoagencia)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table cliente
--
CREATE TABLE cliente (
  codigoCliente INT(11) NOT NULL AUTO_INCREMENT,
  nroContacto INT(11) DEFAULT NULL,
  CI INT(11) DEFAULT NULL,
  direccion VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (codigoCliente)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table renta
--
CREATE TABLE renta (
  codigoRenta INT(11) NOT NULL AUTO_INCREMENT,
  codigoAgencia INT(11) DEFAULT NULL,
  codigoCliente INT(11) DEFAULT NULL,
  fechaInicio DATETIME DEFAULT NULL,
  fechaFin DATETIME DEFAULT NULL,
  PRIMARY KEY (codigoRenta)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table administrativo
--

-- Table servicioderenta.administrativo does not contain any data (it is empty)

-- 
-- Dumping data for table agencia
--

-- Table servicioderenta.agencia does not contain any data (it is empty)

-- 
-- Dumping data for table cliente
--

-- Table servicioderenta.cliente does not contain any data (it is empty)

-- 
-- Dumping data for table renta
--

-- Table servicioderenta.renta does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;