--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/09/2018 15:14:31
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE servicioderenta;

--
-- Drop table `detalles`
--
DROP TABLE IF EXISTS detalles;

--
-- Drop table `servicios`
--
DROP TABLE IF EXISTS servicios;

--
-- Drop table `mecanicos`
--
DROP TABLE IF EXISTS mecanicos;

--
-- Drop table `talleres`
--
DROP TABLE IF EXISTS talleres;

--
-- Drop table `administrativos`
--
DROP TABLE IF EXISTS administrativos;

--
-- Drop table `rentas`
--
DROP TABLE IF EXISTS rentas;

--
-- Drop table `agencias`
--
DROP TABLE IF EXISTS agencias;

--
-- Drop table `autos`
--
DROP TABLE IF EXISTS autos;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Set default database
--
USE servicioderenta;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  codigoCliente int(11) NOT NULL AUTO_INCREMENT,
  nroContacto int(11) NOT NULL,
  ci int(11) NOT NULL,
  direccion varchar(50) NOT NULL,
  PRIMARY KEY (codigoCliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `autos`
--
CREATE TABLE autos (
  codigoAuto int(11) NOT NULL AUTO_INCREMENT,
  tipo varchar(25) NOT NULL,
  capacidad int(11) NOT NULL,
  modelo year(4) NOT NULL,
  estado varchar(10) NOT NULL,
  precio int(11) NOT NULL,
  placa int(11) NOT NULL,
  PRIMARY KEY (codigoAuto)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `placa` on table `autos`
--
ALTER TABLE autos
ADD UNIQUE INDEX placa (placa);

--
-- Create table `agencias`
--
CREATE TABLE agencias (
  codigoAgencia int(11) NOT NULL AUTO_INCREMENT,
  direccion varchar(50) NOT NULL,
  ciudad varchar(25) NOT NULL,
  PRIMARY KEY (codigoAgencia)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `rentas`
--
CREATE TABLE rentas (
  codigoRenta int(11) NOT NULL AUTO_INCREMENT,
  codigoCliente int(11) NOT NULL,
  codigoAgencia int(11) NOT NULL,
  codigoAuto int(11) NOT NULL,
  fechaInicio date NOT NULL,
  fechaFin date NOT NULL,
  PRIMARY KEY (codigoRenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE rentas
ADD CONSTRAINT FK_rentas_codigoAgencia FOREIGN KEY (codigoAgencia)
REFERENCES agencias (codigoAgencia) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE rentas
ADD CONSTRAINT FK_rentas_codigoAuto FOREIGN KEY (codigoAuto)
REFERENCES autos (codigoAuto) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE rentas
ADD CONSTRAINT FK_rentas_codigoCliente FOREIGN KEY (codigoCliente)
REFERENCES clientes (codigoCliente) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `administrativos`
--
CREATE TABLE administrativos (
  codigoAdministrativo int(11) NOT NULL AUTO_INCREMENT,
  codigoAgencia int(11) NOT NULL,
  ci int(11) NOT NULL,
  nroContacto int(11) NOT NULL,
  PRIMARY KEY (codigoAdministrativo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE administrativos
ADD CONSTRAINT FK_administrativos_codigoAgenc FOREIGN KEY (codigoAgencia)
REFERENCES agencias (codigoAgencia) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `talleres`
--
CREATE TABLE talleres (
  codigoTaller int(11) NOT NULL AUTO_INCREMENT,
  direccion varchar(50) NOT NULL,
  capacidad int(11) NOT NULL,
  PRIMARY KEY (codigoTaller)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `mecanicos`
--
CREATE TABLE mecanicos (
  codigoMecanico int(11) NOT NULL AUTO_INCREMENT,
  codigoTaller int(11) NOT NULL,
  ci int(11) NOT NULL,
  nroContacto int(11) NOT NULL,
  PRIMARY KEY (codigoMecanico)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE mecanicos
ADD CONSTRAINT FK_mecanicos_codigoTaller FOREIGN KEY (codigoTaller)
REFERENCES talleres (codigoTaller) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `servicios`
--
CREATE TABLE servicios (
  codigoServicio int(11) NOT NULL AUTO_INCREMENT,
  precio int(11) NOT NULL,
  tipo varchar(50) NOT NULL,
  PRIMARY KEY (codigoServicio)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `detalles`
--
CREATE TABLE detalles (
  codigoDetalle int(11) NOT NULL,
  codigoServicio int(11) NOT NULL,
  codigoRenta int(11) NOT NULL,
  PRIMARY KEY (codigoDetalle)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalles
ADD CONSTRAINT FK_detalles_codigoRenta FOREIGN KEY (codigoRenta)
REFERENCES rentas (codigoRenta) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE detalles
ADD CONSTRAINT FK_detalles_codigoServicio FOREIGN KEY (codigoServicio)
REFERENCES servicios (codigoServicio) ON DELETE CASCADE ON UPDATE CASCADE;

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 442563, 527778, 'vivo aqui.');

-- 
-- Dumping data for table autos
--
INSERT INTO autos VALUES
(2, 'SEDAN', 4, 2013, 'No alquila', 100, 2343),
(3, 'Motocicleta', 1, 2013, 'No alquila', 50, 22343),
(6, 'Sedan', 5, 2010, 'alquilado', 80, 3443);

-- 
-- Dumping data for table agencias
--
INSERT INTO agencias VALUES
(1, 'direccion es esta', 'Ciudad de aqui.');

-- 
-- Dumping data for table talleres
--
-- Table servicioderenta.talleres does not contain any data (it is empty)

-- 
-- Dumping data for table servicios
--
INSERT INTO servicios VALUES
(1, 500, 'Asistencia de remolque'),
(2, 100, 'GPS');

-- 
-- Dumping data for table rentas
--
-- Table servicioderenta.rentas does not contain any data (it is empty)

-- 
-- Dumping data for table mecanicos
--
-- Table servicioderenta.mecanicos does not contain any data (it is empty)

-- 
-- Dumping data for table detalles
--
-- Table servicioderenta.detalles does not contain any data (it is empty)

-- 
-- Dumping data for table administrativos
--
-- Table servicioderenta.administrativos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;