--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/09/2018 15:15:14
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE servicioderenta;

--
-- Drop table `detalles`
--
DROP TABLE IF EXISTS detalles;

--
-- Drop table `autos`
--
DROP TABLE IF EXISTS autos;

--
-- Drop table `servicios`
--
DROP TABLE IF EXISTS servicios;

--
-- Drop table `mecanicos`
--
DROP TABLE IF EXISTS mecanicos;

--
-- Drop table `taller`
--
DROP TABLE IF EXISTS taller;

--
-- Set default database
--
USE servicioderenta;

--
-- Create table `taller`
--
CREATE TABLE taller (
  codigoTaller int(11) NOT NULL AUTO_INCREMENT,
  direccion varchar(50) NOT NULL,
  capacidad int(11) NOT NULL,
  PRIMARY KEY (codigoTaller)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `mecanicos`
--
CREATE TABLE mecanicos (
  codigoMecanico int(11) NOT NULL AUTO_INCREMENT,
  codigoTaller int(11) NOT NULL,
  ci int(11) NOT NULL,
  nroContacto int(11) NOT NULL,
  PRIMARY KEY (codigoMecanico)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE mecanicos
ADD CONSTRAINT FK_mecanicos_codigoTaller FOREIGN KEY (codigoTaller)
REFERENCES taller (codigoTaller) ON DELETE CASCADE;

--
-- Create table `servicios`
--
CREATE TABLE servicios (
  codigoServicio int(11) NOT NULL AUTO_INCREMENT,
  precio int(11) NOT NULL,
  tipo varchar(50) NOT NULL,
  PRIMARY KEY (codigoServicio)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `autos`
--
CREATE TABLE autos (
  codigoAuto int(11) NOT NULL,
  tipo varchar(25) NOT NULL,
  capacidad int(11) NOT NULL,
  modelo year(4) NOT NULL,
  estado varchar(10) NOT NULL,
  precio int(11) NOT NULL,
  placa int(11) NOT NULL,
  PRIMARY KEY (codigoAuto)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `placa` on table `autos`
--
ALTER TABLE autos
ADD UNIQUE INDEX placa (placa);

--
-- Create table `detalles`
--
CREATE TABLE detalles (
  codigoDetalleServicio int(11) NOT NULL AUTO_INCREMENT,
  codigoRenta int(11) DEFAULT NULL,
  codigoAuto int(11) DEFAULT NULL,
  codigoServicio int(11) DEFAULT NULL,
  PRIMARY KEY (codigoDetalleServicio)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalles
ADD CONSTRAINT FK_detalles_codigoAuto FOREIGN KEY (codigoAuto)
REFERENCES autos (codigoAuto) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detalles
ADD CONSTRAINT FK_detalles_codigoServicio FOREIGN KEY (codigoServicio)
REFERENCES servicios (codigoServicio) ON DELETE CASCADE;

-- 
-- Dumping data for table taller
--
-- Table servicioderenta.taller does not contain any data (it is empty)

-- 
-- Dumping data for table servicios
--
-- Table servicioderenta.servicios does not contain any data (it is empty)

-- 
-- Dumping data for table autos
--
-- Table servicioderenta.autos does not contain any data (it is empty)

-- 
-- Dumping data for table mecanicos
--
-- Table servicioderenta.mecanicos does not contain any data (it is empty)

-- 
-- Dumping data for table detalles
--
-- Table servicioderenta.detalles does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;